/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.gdse41.sem1project.view.panels;

import edu.gdse41.sem1project.controller.ControllerFactory;
import edu.gdse41.sem1project.controller.custom.GuestController;
import edu.gdse41.sem1project.dto.GuestDTO;
import edu.gdse41.sem1project.view.Admin;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hansani Kariyawasam
 */
public class AdminViewGuestHistory extends javax.swing.JPanel {
    
    private GuestController ctrlGuest;

    /**
     * Creates new form AdminViewGuestHistory
     */
    public AdminViewGuestHistory() {
        initComponents();
        ctrlGuest=(GuestController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.GUEST);
        loadTable();
        loadGuestIDs();
        
    }
    
    private void loadGuestIDs(){
        String agent=(String) cbAgent.getSelectedItem();
        
            try {
                ArrayList<String> ids=ctrlGuest.getAllGuestHistroyIDs(null);
                for (String id : ids) {
                    cbId.addItem(id);
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminViewGuestHistory.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminViewGuestHistory.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }
    
    private void loadTable(){
        try {
            ArrayList<GuestDTO> guestDetails=ctrlGuest.loadGuestDetails();
            DefaultTableModel dtm=(DefaultTableModel) detailTable.getModel();
            for (GuestDTO g : guestDetails) {
                Object []rowData={g.getGuestID(),g.getAgent(),g.getFName(),g.getLName(),g.getDOB(),g.getNationality(),g.getNIC(),g.getPassport(),g.getTel()};
                dtm.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminViewGuestHistory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminViewGuestHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbAgent = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtl_name = new javax.swing.JTextField();
        txtnatinality = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        lblSave = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpassport = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        cbId = new javax.swing.JComboBox();
        txtf_name = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 620));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        detailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Guest ID", "Agent", "First Name", "Last Name", "Date Of Birth", "Nationality", "NIC", "Passport No", "Mobile Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detailTable.getTableHeader().setReorderingAllowed(false);
        detailTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(detailTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 900, 270));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("First Name :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 90, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Guset ID :");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Agent :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 80, 30));

        cbAgent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Default", "AirBnB", "Booking.Com", "Agoda", "Direct" }));
        cbAgent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAgentItemStateChanged(evt);
            }
        });
        cbAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgentActionPerformed(evt);
            }
        });
        add(cbAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 110, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("NIC :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Nationality :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Last Name:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 150, 30));

        txtl_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 180, 30));

        txtnatinality.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtnatinality, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 180, 30));

        txtNIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 180, 30));

        lblSave.setBackground(new java.awt.Color(221, 188, 9));
        lblSave.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setText("Save Changes");
        lblSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSave.setOpaque(true);
        lblSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaveMouseExited(evt);
            }
        });
        add(lblSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, 190, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Mobile Number :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 120, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Date Of Birth :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 150, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Passport Number :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 140, 30));

        txtpassport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtpassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, 180, 30));

        txtdob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 180, 30));

        txttel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 180, 30));

        cbId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbIdItemStateChanged(evt);
            }
        });
        add(cbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 110, 30));
        add(txtf_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void cbAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAgentActionPerformed

    private void cbAgentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAgentItemStateChanged
        String agent=(String) cbAgent.getSelectedItem();
        if(agent!="Default"){
            cbId.removeAllItems();
            try {
                ArrayList<String> ids=ctrlGuest.getAllGuestHistroyIDs(agent);
                for (String id : ids) {
                    cbId.addItem(id);
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminViewGuestHistory.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminViewGuestHistory.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            cbId.removeAllItems();
            try {
                ArrayList<String> ids=ctrlGuest.getAllGuestHistroyIDs(null);
                for (String id : ids) {
                    cbId.addItem(id);
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminViewGuestHistory.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminViewGuestHistory.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbAgentItemStateChanged

    private void detailTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailTableMouseClicked
        Admin.pnlViewReports.setVisible(false);
        DefaultTableModel dtm=(DefaultTableModel) detailTable.getModel();
        cbAgent.setSelectedItem(dtm.getValueAt(detailTable.getSelectedRow(), 1));
        cbId.setSelectedItem(dtm.getValueAt(detailTable.getSelectedRow(), 0));
    }//GEN-LAST:event_detailTableMouseClicked

    private void lblSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseClicked
        GuestDTO guest=new GuestDTO((String)cbId.getSelectedItem(),
                                     txtf_name.getText(),
                                     txtl_name.getText(),
                                     txtdob.getText(),
                                     txtnatinality.getText(),
                                     txtNIC.getText(),
                                     txtpassport.getText(),
                                     txttel.getText());
        try {
            boolean result=ctrlGuest.update(guest);
            if(result){
                DefaultTableModel dtm=(DefaultTableModel) detailTable.getModel();
                for(int i=0;i<detailTable.getRowCount();i++){
                    String id=(String) cbId.getSelectedItem();
                    if(id == null ? (String)dtm.getValueAt(i, 0) == null : id.equals((String)dtm.getValueAt(i, 0))){
                        dtm.setValueAt(txtf_name.getText(), i, 2);
                        dtm.setValueAt(txtl_name.getText(), i, 3);
                        dtm.setValueAt(txtdob.getText(), i, 4);
                        dtm.setValueAt(txtnatinality.getText(), i, 5);
                        dtm.setValueAt(txtNIC.getText(), i, 6);
                        dtm.setValueAt(txtpassport.getText(), i, 7);
                        dtm.setValueAt(txttel.getText(), i, 8);
                    }
                }
                JOptionPane.showMessageDialog(this, "Saved changes");
            }
        } catch (Exception ex) {
            Logger.getLogger(AdminViewGuestHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblSaveMouseClicked

    private void cbIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbIdItemStateChanged
        String id=(String) cbId.getSelectedItem();
        setText(id);
    }//GEN-LAST:event_cbIdItemStateChanged

    private void lblSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseEntered
        lblSave.setBackground(new Color(255,162,0));
        lblSave.setOpaque(true);
    }//GEN-LAST:event_lblSaveMouseEntered

    private void lblSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseExited
        lblSave.setBackground(new Color(2221,188,9));
        lblSave.setOpaque(true);
    }//GEN-LAST:event_lblSaveMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Admin.pnlViewReports.setVisible(false);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbAgent;
    private javax.swing.JComboBox cbId;
    private javax.swing.JTable detailTable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSave;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtf_name;
    private javax.swing.JTextField txtl_name;
    private javax.swing.JTextField txtnatinality;
    private javax.swing.JTextField txtpassport;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables

    private void setText(String id) {
        try {
            GuestDTO g=ctrlGuest.search(id);
            txtf_name.setText(g.getFName());
            txtl_name.setText(g.getLName());
            txtNIC.setText(g.getNIC());
            txtdob.setText(g.getDOB());
            txtnatinality.setText(g.getNationality());
            txtpassport.setText(g.getPassport());
            txttel.setText(g.getTel());
        } catch (Exception ex) {
            //Logger.getLogger(AdminViewGuestHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
