/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.gdse41.sem1project.view.panels;

import edu.gdse41.sem1project.controller.ControllerFactory;
import edu.gdse41.sem1project.controller.custom.GuestController;
import edu.gdse41.sem1project.controller.custom.ReservationController;
import edu.gdse41.sem1project.controller.custom.impl.DataValidation;
import edu.gdse41.sem1project.dao.db.ConnectionFactory;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import edu.gdse41.sem1project.dto.GuestDTO;
import edu.gdse41.sem1project.dto.ReservationDTO;
import edu.gdse41.sem1project.dto.ReservationDetailsDTO;
import edu.gdse41.sem1project.dto.RoomDTO;
import edu.gdse41.sem1project.id.IDGenerator;
import edu.gdse41.sem1project.view.JasperReportViewer;
import edu.gdse41.sem1project.view.Reception;
import edu.gdse41.sem1project.view.panels.titles.ReservationTitle;
import java.awt.Color;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.SwingUtilities;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Hansani Kariyawasam
 */
public class AgentAddGuest extends javax.swing.JPanel {
    
    public static String guestID;
    public static String guestName;
    public static String guestTel;
    public static String checkIn;
    public static String checkOut;
    public static String resId;
    public static String agent;
    private GuestController ctrlGuest;
    private ReservationController ctrlRes;

    /**
     * Creates new form AgentAddGuest
     */
    public AgentAddGuest() {
        initComponents();
        ctrlGuest = (GuestController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.GUEST);
        ctrlRes=(ReservationController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.RESERVATION);
        setGuestID();
        try {
            resId=IDGenerator.getNewID("Reservation", "Res_id", "R");
        } catch (SQLException ex) {
            Logger.getLogger(AgentAddGuest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AgentAddGuest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setGuestID(){
        try {
            String id=IDGenerator.getNewID("guest", "gid", "C");
            txtGusetID.setText(id);
        } catch (SQLException ex) {
            Logger.getLogger(AgentAddGuest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AgentAddGuest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtGusetID = new javax.swing.JTextField();
        txtf_name = new javax.swing.JTextField();
        txtl_name = new javax.swing.JTextField();
        txtCheckIn = new org.jdesktop.swingx.JXDatePicker();
        txtCheckOut = new org.jdesktop.swingx.JXDatePicker();
        txtnatinality = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtpassport = new javax.swing.JTextField();
        txtdob = new org.jdesktop.swingx.JXDatePicker();
        txtEmail = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblNext1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblErrorTel = new javax.swing.JLabel();
        cmbAgent = new javax.swing.JComboBox();
        lblPrint = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 620));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Guset ID :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 150, 30));

        txtGusetID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGusetID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGusetIDActionPerformed(evt);
            }
        });
        add(txtGusetID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 200, 30));

        txtf_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_nameActionPerformed(evt);
            }
        });
        add(txtf_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 200, 30));

        txtl_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 200, 30));
        add(txtCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 200, 30));

        txtCheckOut.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCheckOutPropertyChange(evt);
            }
        });
        add(txtCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 200, 30));

        txtnatinality.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnatinality.setName("nic"); // NOI18N
        add(txtnatinality, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 200, 30));

        txtNIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNIC.setName("nic"); // NOI18N
        txtNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNICKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNICKeyTyped(evt);
            }
        });
        add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 200, 30));

        txtpassport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtpassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 200, 30));
        add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 200, 30));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setName("email"); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 200, 30));

        txttel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttel.setName("telNo"); // NOI18N
        txttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelActionPerformed(evt);
            }
        });
        txttel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttelKeyReleased(evt);
            }
        });
        add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Check-Out-Date :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 170, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Check-In-Date :");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 150, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Last Name:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Contact Details");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 240, 60));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("E-mail :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 150, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Mobile Number :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 150, 30));

        lblBack.setBackground(new java.awt.Color(221, 188, 9));
        lblBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setText("Back");
        lblBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBack.setName("lblMain"); // NOI18N
        lblBack.setOpaque(true);
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackMouseExited(evt);
            }
        });
        add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 170, 50));

        lblNext1.setBackground(new java.awt.Color(221, 188, 9));
        lblNext1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblNext1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNext1.setText("Next");
        lblNext1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNext1.setName("lblMain"); // NOI18N
        lblNext1.setOpaque(true);
        lblNext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNext1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNext1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNext1MouseExited(evt);
            }
        });
        add(lblNext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 170, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Date Of Birth :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Agent :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 150, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Passport Number :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 200, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("NIC :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 150, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Nationality :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("First Name :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 150, 30));

        lblErrorTel.setForeground(new java.awt.Color(255, 0, 0));
        add(lblErrorTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 160, 20));

        cmbAgent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Booking.Com", "Agoda", "AirBnB" }));
        add(cmbAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 140, 30));

        lblPrint.setBackground(new java.awt.Color(221, 188, 9));
        lblPrint.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblPrint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrint.setText("Registration Card");
        lblPrint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPrint.setName("lblMain"); // NOI18N
        lblPrint.setOpaque(true);
        lblPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPrintMouseExited(evt);
            }
        });
        add(lblPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 200, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtGusetIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGusetIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGusetIDActionPerformed

    private void txtf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_nameActionPerformed

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelActionPerformed

    private void txttelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelKeyReleased
        
    }//GEN-LAST:event_txttelKeyReleased

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        //new Availability().setVisible(true);
        
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblNext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNext1MouseClicked
        ArrayList<Object[]> rows=AgentReserveRoom.rows;
        ArrayList<RoomDTO> roomsData=new ArrayList<>();
        boolean email = true;
        boolean tel = true;
        boolean nic = true;
        try {
            email = DataValidation.Validation(txtEmail);
            tel=DataValidation.Validation(txttel);
            nic=DataValidation.Validation(txtNIC);
        } catch (SQLException ex) {
            Logger.getLogger(AgentAddGuest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AgentAddGuest.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(!email || !tel || !nic){
            if(!email){
               txtEmail.setText("");
           }
           if(!tel){
                txttel.setText("");
            }
            if(!nic){
               txtNIC.setText("");
            }
            return;
        }else{
            for(Object[]  row: rows){
                RoomDTO r=new RoomDTO(row[0].toString(),row[1].toString(),row[2].toString(),Double.parseDouble(row[3].toString()));
                roomsData.add(r);
            }
            Date date=txtdob.getDate();
            Date d=new Date();
            Date In=txtCheckIn.getDate();
            Date Out=txtCheckOut.getDate();
            DateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
            String dob=dateFormat.format(date);
            checkIn=dateFormat.format(In);
            checkOut=dateFormat.format(Out);
            String curDate=dateFormat.format(d);
            try {
                guestID=txtGusetID.getText();
                guestTel=txttel.getText();
                GuestDTO g1=new GuestDTO(guestID,txtf_name.getText(),txtl_name.getText(),dob,txtnatinality.getText(),txtpassport.getText(),txtNIC.getText(),guestTel);
                guestName=g1.getFName()+" "+g1.getLName();
                agent=(String) cmbAgent.getSelectedItem();
                ReservationDTO r1=new ReservationDTO(resId,checkIn,checkOut,agent);
                ArrayList<ReservationDetailsDTO> resDetails=new ArrayList<>();
                int count=0;
                String lastId=IDGenerator.getNewID("ReservationDetails", "ResDetails_ID", "D");
                String resDetails_id;
                for(RoomDTO r: roomsData){
                    if(count==0){
                        resDetails_id=IDGenerator.getNewID("ReservationDetails", "ResDetails_ID", "D");
                    }else{
                        lastId=IDGenerator.getNewID(lastId, "D");
                        resDetails_id=lastId;
                    }
                    ReservationDetailsDTO res=new ReservationDetailsDTO(resDetails_id,guestID,r.getRoomID(),resId,curDate,r.getRoomPrice());
                    resDetails.add(res);
                    count++;
                }
                GuestDTO details=new GuestDTO(guestID,txtf_name.getText(),txtl_name.getText(),txtnatinality.getText(),dob,txtpassport.getText(),txtNIC.getText(),guestTel,r1,resDetails);
                boolean result=ctrlGuest.addNewReservation(details);
            } catch (SQLException ex) {
                Logger.getLogger(AddGuest.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddGuest.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(AgentAddGuest.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            Reception frmMain=(Reception) SwingUtilities.getWindowAncestor(this);
            frmMain.pnlMain.removeAll();
            AgentReservation a=new AgentReservation();
            frmMain.pnlMain.add(a);
            frmMain.pnltitle.removeAll();
            ReservationTitle title=new ReservationTitle();
            frmMain.pnltitle.add(title);
            frmMain.pnlMain.updateUI();  

        }
    }//GEN-LAST:event_lblNext1MouseClicked

    private void txtNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyReleased
        
    }//GEN-LAST:event_txtNICKeyReleased

    private void txtNICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyTyped

    }//GEN-LAST:event_txtNICKeyTyped

    private void lblPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintMouseClicked
        Date date=txtdob.getDate();
        Date d1=txtCheckIn.getDate();
        Date d2=txtCheckOut.getDate();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String dob=sdf.format(date);
        String cIn=sdf.format(d1);
        String cOut=sdf.format(d2);
        String agent=(String) cmbAgent.getSelectedItem();
        try {
            Connection con=ConnectionFactory.getInstance().getConnection();
            JasperReport compiledReport=(JasperReport) JRLoader.loadObject(AddGuest.class.getResourceAsStream("/edu/gdse41/sem1project/reports/Registration.jasper"));
            Map<String,Object> parameters=new HashMap<>();
            parameters.put("agent", agent);
            parameters.put("res_id", resId);
            parameters.put("checkIn", cIn);
            parameters.put("checkOut", cOut);
            parameters.put("noOfAdults", "");
            parameters.put("noOfKids", "");
            parameters.put("lastName", txtl_name.getText());
            parameters.put("nic", txtNIC.getText());
            parameters.put("firstName", txtf_name.getText());
            parameters.put("nationality", txtnatinality.getText());
            parameters.put("dob", dob);
            parameters.put("passport", txtpassport.getText());
            parameters.put("tel", txttel.getText());
            parameters.put("email", txtEmail.getText());
            JasperPrint filledReport=JasperFillManager.fillReport(compiledReport, parameters, new JREmptyDataSource());
            JasperReportViewer jasperViewer=new JasperReportViewer(filledReport);
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(AddGuest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblPrintMouseClicked

    private void lblPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintMouseEntered
        lblPrint.setBackground(new Color(255,162,0));
        lblPrint.setOpaque(true);
    }//GEN-LAST:event_lblPrintMouseEntered

    private void lblPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintMouseExited
        lblPrint.setBackground(new Color(221,188,9));
        lblPrint.setOpaque(true);
    }//GEN-LAST:event_lblPrintMouseExited

    private void lblBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseEntered
        lblBack.setBackground(new Color(255,162,0));
        lblBack.setOpaque(true);
    }//GEN-LAST:event_lblBackMouseEntered

    private void lblBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseExited
        lblBack.setBackground(new Color(221,188,9));
        lblBack.setOpaque(true);
    }//GEN-LAST:event_lblBackMouseExited

    private void lblNext1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNext1MouseEntered
        lblNext1.setBackground(new Color(255,162,0));
        lblNext1.setOpaque(true);
    }//GEN-LAST:event_lblNext1MouseEntered

    private void lblNext1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNext1MouseExited
        lblNext1.setBackground(new Color(221,188,9));
        lblNext1.setOpaque(true);
    }//GEN-LAST:event_lblNext1MouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Reception.reserveRoomPanel.setVisible(false);
        Reception.pnlViewReports.setVisible(false);
    }//GEN-LAST:event_formMouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        txtCheckIn.getMonthView().setLowerBound(new Date());
    }//GEN-LAST:event_formPropertyChange

    private void txtCheckOutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCheckOutPropertyChange
        txtCheckOut.getMonthView().setLowerBound(txtCheckIn.getDate());
    }//GEN-LAST:event_txtCheckOutPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbAgent;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblErrorTel;
    private javax.swing.JLabel lblNext1;
    private javax.swing.JLabel lblPrint;
    private org.jdesktop.swingx.JXDatePicker txtCheckIn;
    private org.jdesktop.swingx.JXDatePicker txtCheckOut;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGusetID;
    private javax.swing.JTextField txtNIC;
    private org.jdesktop.swingx.JXDatePicker txtdob;
    private javax.swing.JTextField txtf_name;
    private javax.swing.JTextField txtl_name;
    private javax.swing.JTextField txtnatinality;
    private javax.swing.JTextField txtpassport;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
