/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.gdse41.sem1project.view.panels;

import edu.gdse41.sem1project.controller.ControllerFactory;
import edu.gdse41.sem1project.controller.custom.PaymentController;
import edu.gdse41.sem1project.dto.PaymentDTO;
import edu.gdse41.sem1project.id.IDGenerator;
import edu.gdse41.sem1project.view.Reception;
import static edu.gdse41.sem1project.view.panels.AgentAddGuest.resId;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hansani Kariyawasam
 */
public class AgentReservation extends javax.swing.JPanel {
    private PaymentController ctrlPayment;

    /**
     * Creates new form AgentReservation
     */
    public AgentReservation() {
        initComponents();
        ctrlPayment=(PaymentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.PAYMENT);
        setGuestDetails();
        setResID();
        setReservationDate();
        calculateNights();
        loadTableData();
    }
    
    private void loadTableData(){
        ArrayList<Object[]> rows=AgentReserveRoom.rows;
        for(Object[] row:rows){
            DefaultTableModel dtm=(DefaultTableModel)roomTable.getModel();
            dtm.addRow(row);
        }
    }
    
    private void calculateNights(){
        String checkIn=AgentAddGuest.checkIn;
        String checkOut=AgentAddGuest.checkOut;
        LocalDate cIn=LocalDate.parse(checkIn);
        LocalDate cOut=LocalDate.parse(checkOut);
        int nights=cOut.compareTo(cIn);
        txtNoOfNights1.setText(""+nights);
    }
    
    private void setReservationDate(){
        Date d=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(d);
        txtResDate.setText(date);
    }
    
    private void setResID(){
        String id=AgentAddGuest.resId;
        txtResID.setText(id);
       
    }
    
    private void setGuestDetails(){
        lblGuestID.setText(AgentAddGuest.guestID);
        lblName.setText(AgentAddGuest.guestName);
        lblTel.setText(AgentAddGuest.guestTel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtResID = new javax.swing.JTextField();
        txtResDate = new javax.swing.JTextField();
        txtNoOfNights1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomTable = new javax.swing.JTable();
        lblConfirm = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGuestID = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 620));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Reservation ID :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 170, 30));

        txtResID.setEditable(false);
        txtResID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtResID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResIDActionPerformed(evt);
            }
        });
        add(txtResID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 200, 30));

        txtResDate.setEditable(false);
        txtResDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtResDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResDateActionPerformed(evt);
            }
        });
        add(txtResDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 200, 30));

        txtNoOfNights1.setEditable(false);
        txtNoOfNights1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtNoOfNights1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 200, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Booking Summary");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 280, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Guest ID :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 160, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Guest Name :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Mobile Number :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 160, 30));

        roomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Room Type", "Status", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        roomTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(roomTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, 140));

        lblConfirm.setBackground(new java.awt.Color(221, 188, 9));
        lblConfirm.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirm.setText("Confirm");
        lblConfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblConfirm.setName("lblMain"); // NOI18N
        lblConfirm.setOpaque(true);
        lblConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConfirmMouseExited(evt);
            }
        });
        add(lblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, 170, 50));

        lblBack.setBackground(new java.awt.Color(221, 188, 9));
        lblBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setText("Back");
        lblBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBack.setName("lblMain"); // NOI18N
        lblBack.setOpaque(true);
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackMouseExited(evt);
            }
        });
        add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 170, 50));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(153, 153, 153));
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 350, 30));

        lblGuestID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGuestID.setForeground(new java.awt.Color(153, 153, 153));
        add(lblGuestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 200, 30));

        lblTel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTel.setForeground(new java.awt.Color(153, 153, 153));
        add(lblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Reservation Date :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 180, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("No Of Nights :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtResIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResIDActionPerformed

    private void txtResDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResDateActionPerformed

    private void lblConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseClicked
        DefaultTableModel dtm=(DefaultTableModel) roomTable.getModel();
        double amount=0;
        for(int i=0;i<roomTable.getRowCount();i++){
            amount=amount+(double)dtm.getValueAt(i, 3);
        }
        
        String pid;
        try {
            pid = IDGenerator.getNewID("Payment", "PID", "P");
            String resId=txtResID.getText();
            String curDate=txtResDate.getText();
            String agent=AgentAddGuest.agent;
            double amountPaid;
            if(agent!="Booking.Com"){
                amountPaid=amount*Double.parseDouble(txtNoOfNights1.getText());
            }else{
                amountPaid=0;
            }
            PaymentDTO p1=new PaymentDTO(pid,resId,amountPaid,curDate,null);
            boolean result=ctrlPayment.add(p1);
        } catch (SQLException ex) {
            Logger.getLogger(AgentReservation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AgentReservation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AgentReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
        Availability.rows.clear();
    }//GEN-LAST:event_lblConfirmMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        //new AddGuest().setVisible(true);
        
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseEntered
        lblBack.setBackground(new Color(255,162,0));
        lblBack.setOpaque(true);
    }//GEN-LAST:event_lblBackMouseEntered

    private void lblBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseExited
        lblBack.setBackground(new Color(221,188,9));
        lblBack.setOpaque(true);
    }//GEN-LAST:event_lblBackMouseExited

    private void lblConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseEntered
        lblConfirm.setBackground(new Color(255,162,0));
        lblConfirm.setOpaque(true);
    }//GEN-LAST:event_lblConfirmMouseEntered

    private void lblConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseExited
        lblConfirm.setBackground(new Color(221,188,9));
        lblConfirm.setOpaque(true);
    }//GEN-LAST:event_lblConfirmMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Reception.reserveRoomPanel.setVisible(false);
        Reception.pnlViewReports.setVisible(false);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblGuestID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTel;
    private javax.swing.JTable roomTable;
    private javax.swing.JTextField txtNoOfNights1;
    private javax.swing.JTextField txtResDate;
    private javax.swing.JTextField txtResID;
    // End of variables declaration//GEN-END:variables
}
