/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.gdse41.sem1project.view.panels;

import edu.gdse41.sem1project.controller.ControllerFactory;
import edu.gdse41.sem1project.controller.custom.RoomController;
import edu.gdse41.sem1project.controller.custom.impl.RoomControllerImpl;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.table.DefaultTableModel;
import edu.gdse41.sem1project.dto.RoomDTO;
import edu.gdse41.sem1project.view.Reception;
import edu.gdse41.sem1project.view.panels.titles.GuestDetlsTitle;
import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author Hansani Kariyawasam
 */
public class AgentReserveRoom extends javax.swing.JPanel {
    
    public static ArrayList<Object[]> rows=new ArrayList<>();
    private RoomController ctrlRm;

    /**
     * Creates new form AgentReserveRoom
     */
    public AgentReserveRoom() {
        initComponents();
        
        ctrlRm=(RoomControllerImpl) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ROOM);
        loadAvailability();
    }
    
    private void loadAvailability(){
        try {
            ArrayList<RoomDTO> roomList=ctrlRm.view();
            DefaultTableModel dtm=(DefaultTableModel)table1.getModel();
            dtm.setRowCount(0);
            for(RoomDTO r1:roomList){
                Object [] rowData={r1.getRoomID(),r1.getRoomType(),r1.getStatus(),r1.getRoomPrice()};
                dtm.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Availability.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Availability.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AgentReserveRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNext = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        lblReserve = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 620));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNext.setBackground(new java.awt.Color(221, 188, 9));
        lblNext.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNext.setText("Next");
        lblNext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNext.setName("lblMain"); // NOI18N
        lblNext.setOpaque(true);
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNextMouseExited(evt);
            }
        });
        add(lblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, 170, 50));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Room Type", "Status", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table1.getTableHeader().setReorderingAllowed(false);
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 850, 160));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Room Type", "Status", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(table2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 850, 160));

        lblReserve.setBackground(new java.awt.Color(221, 188, 9));
        lblReserve.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblReserve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReserve.setText("Reserve Room");
        lblReserve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblReserve.setName("lblMain"); // NOI18N
        lblReserve.setOpaque(true);
        lblReserve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReserveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReserveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReserveMouseExited(evt);
            }
        });
        add(lblReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, 160, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(221, 188, 9));
        jLabel2.setText("Reserved Rooms");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 270, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(221, 188, 9));
        jLabel3.setText("Available Rooms");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 270, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        if(table2.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"First you must select and reserve a room","Warning Message",WARNING_MESSAGE);
        }else{
            Reception frmMain=(Reception) SwingUtilities.getWindowAncestor(this);
            frmMain.pnlMain.removeAll();
            AgentAddGuest d=new AgentAddGuest();
            frmMain.pnlMain.add(d);
            frmMain.pnltitle.removeAll();
            GuestDetlsTitle title=new GuestDetlsTitle();
            frmMain.pnltitle.add(title);
            frmMain.pnlMain.updateUI();
            
        }
    }//GEN-LAST:event_lblNextMouseClicked

    private void lblReserveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReserveMouseClicked
        DefaultTableModel dtm=(DefaultTableModel)table1.getModel();
        Object [] rowData={dtm.getValueAt(table1.getSelectedRow(),0),dtm.getValueAt(table1.getSelectedRow(),1),dtm.getValueAt(table1.getSelectedRow(),2),dtm.getValueAt(table1.getSelectedRow(),3)};
        rows.add(rowData);
        dtm.removeRow(table1.getSelectedRow());
        DefaultTableModel dtm2=(DefaultTableModel)table2.getModel();
        dtm2.addRow(rowData);
    }//GEN-LAST:event_lblReserveMouseClicked

    private void lblReserveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReserveMouseEntered
        lblReserve.setBackground(new Color(255,162,0));
        lblReserve.setOpaque(true);
    }//GEN-LAST:event_lblReserveMouseEntered

    private void lblReserveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReserveMouseExited
        lblReserve.setBackground(new Color(221,188,9));
        lblReserve.setOpaque(true);
    }//GEN-LAST:event_lblReserveMouseExited

    private void lblNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseEntered
        lblNext.setBackground(new Color(255,162,0));
        lblNext.setOpaque(true);
    }//GEN-LAST:event_lblNextMouseEntered

    private void lblNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseExited
        lblNext.setBackground(new Color(221,188,9));
        lblNext.setOpaque(true);
    }//GEN-LAST:event_lblNextMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Reception.reserveRoomPanel.setVisible(false);
        Reception.pnlViewReports.setVisible(false);
    }//GEN-LAST:event_formMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        Reception.reserveRoomPanel.setVisible(false);
        Reception.pnlViewReports.setVisible(false);
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        Reception.reserveRoomPanel.setVisible(false);
        Reception.pnlViewReports.setVisible(false);
    }//GEN-LAST:event_table1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblReserve;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
