/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.gdse41.sem1project.view.panels;

import edu.gdse41.sem1project.controller.ControllerFactory;
import edu.gdse41.sem1project.controller.custom.GuestController;
import edu.gdse41.sem1project.controller.custom.ReservationController;
import edu.gdse41.sem1project.controller.custom.ReservationDetailsController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import edu.gdse41.sem1project.dto.GuestDTO;
import edu.gdse41.sem1project.dto.ReservationDetailsDTO;
import edu.gdse41.sem1project.view.Reception;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hansani Kariyawasam
 */
public class CancelReservation extends javax.swing.JPanel {
    
    private GuestController ctrlGuest;
    private ReservationDetailsController ctrlResDetails;
    private ReservationController ctrlRes;

    /**
     * Creates new form CancelReservation
     */
    public CancelReservation() {
        initComponents();
        ctrlResDetails=(ReservationDetailsController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.RES_DETAILS);
        ctrlRes= (ReservationController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.RESERVATION);
        ctrlGuest= (GuestController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.GUEST);
        loadGuestIDs();
        loadResIDs();
    }
    
    private void loadGuestIDs(){
        try {
            ArrayList<String> guestIDs=ctrlGuest.getAllGuestIDs();
            for(int i=0;i<guestIDs.size();i++){
                CBGuestID.addItem(guestIDs.get(i));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CancelReservation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CancelReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadResIDs(){
        try {
            ArrayList<String> resIDs=ctrlRes.getAllResIDs();
            for(String id : resIDs){
                CBResID.addItem(id);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CancelReservation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CancelReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGuestName1 = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        CBGuestID = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtResDate = new javax.swing.JTextField();
        CBResID = new javax.swing.JComboBox();
        lblSearch = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCancelRes = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 620));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGuestName1.setEditable(false);
        txtGuestName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGuestName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuestName1ActionPerformed(evt);
            }
        });
        add(txtGuestName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 200, 30));

        txttel.setEditable(false);
        txttel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelActionPerformed(evt);
            }
        });
        add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 200, 30));

        CBGuestID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBGuestIDItemStateChanged(evt);
            }
        });
        add(CBGuestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 130, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Mobile Number :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 150, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Guset ID :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 150, 30));

        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservation ID ", "Guest ID", "Reserved Date", "Guest Name", "Mobile Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detailsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(detailsTable);
        if (detailsTable.getColumnModel().getColumnCount() > 0) {
            detailsTable.getColumnModel().getColumn(0).setResizable(false);
            detailsTable.getColumnModel().getColumn(1).setResizable(false);
            detailsTable.getColumnModel().getColumn(2).setResizable(false);
            detailsTable.getColumnModel().getColumn(3).setResizable(false);
            detailsTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 890, 220));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Reserved Date :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 180, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Reservation ID :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, 30));

        txtResDate.setEditable(false);
        txtResDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResDateActionPerformed(evt);
            }
        });
        add(txtResDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 200, 30));

        CBResID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBResIDItemStateChanged(evt);
            }
        });
        add(CBResID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 130, 30));

        lblSearch.setBackground(new java.awt.Color(221, 188, 9));
        lblSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setText("Search");
        lblSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSearch.setName("lblMain"); // NOI18N
        lblSearch.setOpaque(true);
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchMouseExited(evt);
            }
        });
        add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 120, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Guest Name :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 150, 30));

        lblCancelRes.setBackground(new java.awt.Color(221, 188, 9));
        lblCancelRes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCancelRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelRes.setText("Cancel Reservation");
        lblCancelRes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCancelRes.setName("lblMain"); // NOI18N
        lblCancelRes.setOpaque(true);
        lblCancelRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelResMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelResMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelResMouseExited(evt);
            }
        });
        add(lblCancelRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, 150, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtGuestName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuestName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuestName1ActionPerformed

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelActionPerformed

    private void CBGuestIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBGuestIDItemStateChanged
        String id=(String)CBGuestID.getSelectedItem();
        try {
            GuestDTO g1=ctrlGuest.search(id);
            txtGuestName1.setText(g1.getFName()+" "+g1.getLName());
            txttel.setText(g1.getTel());
        } catch (SQLException ex) {
            Logger.getLogger(CancelReservation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CancelReservation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CancelReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CBGuestIDItemStateChanged

    private void txtResDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResDateActionPerformed

    private void CBResIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBResIDItemStateChanged
        String id=(String)CBResID.getSelectedItem();
        try {
            ReservationDetailsDTO rd=ctrlResDetails.search(id);
            txtResDate.setText(rd.getReservedDate());
            CBGuestID.setSelectedItem(rd.getGuestID());
        } catch (SQLException ex) {
            Logger.getLogger(CancelReservation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CancelReservation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CancelReservation.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_CBResIDItemStateChanged

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        String id=(String) CBGuestID.getSelectedItem();
        try {
            ArrayList<ReservationDetailsDTO> details=ctrlResDetails.resDetails(id);
            DefaultTableModel dtm=(DefaultTableModel) detailsTable.getModel();
            dtm.getDataVector().removeAllElements();
            detailsTable.repaint();
            for (ReservationDetailsDTO d : details) {
                Object[] rowData={d.getResID(),d.getGuestID(),d.getReservedDate(),d.getFname()+" "+d.getLname(),d.getTel()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(CancelReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblSearchMouseClicked

    private void lblCancelResMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelResMouseClicked
        DefaultTableModel dtm=(DefaultTableModel) detailsTable.getModel();
        if(detailsTable.getSelectedRow()!=-1){    
            String id=(String) dtm.getValueAt(detailsTable.getSelectedRow(), 0);
            try {
                boolean result=ctrlRes.delete(id);
                if(result){
                    int res=JOptionPane.showConfirmDialog(this, "Do you want to cancel this reservation", "Confirmation", JOptionPane.YES_NO_OPTION);
                    if(res==0){
                        JOptionPane.showMessageDialog(this, "Successfully canceled");
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(CancelReservation.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Please select a reservation");
        }
    }//GEN-LAST:event_lblCancelResMouseClicked

    private void lblSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseEntered
        lblSearch.setBackground(new Color(255,162,0));
        lblSearch.setOpaque(true);
    }//GEN-LAST:event_lblSearchMouseEntered

    private void lblSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseExited
        lblSearch.setBackground(new Color(221,188,9));
        lblSearch.setOpaque(true);
    }//GEN-LAST:event_lblSearchMouseExited

    private void lblCancelResMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelResMouseEntered
        lblCancelRes.setBackground(new Color(255,162,0));
        lblCancelRes.setOpaque(true);
    }//GEN-LAST:event_lblCancelResMouseEntered

    private void lblCancelResMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelResMouseExited
        lblCancelRes.setBackground(new Color(221,188,9));
        lblCancelRes.setOpaque(true);
    }//GEN-LAST:event_lblCancelResMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Reception.reserveRoomPanel.setVisible(false);
        Reception.pnlViewReports.setVisible(false);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBGuestID;
    private javax.swing.JComboBox CBResID;
    private javax.swing.JTable detailsTable;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCancelRes;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTextField txtGuestName1;
    private javax.swing.JTextField txtResDate;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
