/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.gdse41.sem1project.view.panels;

import edu.gdse41.sem1project.controller.ControllerFactory;
import edu.gdse41.sem1project.controller.custom.PaymentController;
import edu.gdse41.sem1project.dto.PaymentDTO;
import edu.gdse41.sem1project.dto.RoomDTO;
import edu.gdse41.sem1project.id.IDGenerator;
import edu.gdse41.sem1project.view.Reception;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;

/**
 *
 * @author Hansani Kariyawasam
 */
public class Payment extends javax.swing.JPanel {
    private double total=0;
    private PaymentController ctrlPayment;

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        creditDebitPanel.setVisible(false);
        ctrlPayment=(PaymentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.PAYMENT);
        setSystemDate();
        setGuestID_ResID();
        setPaymentDetails();
    }
    
    private void setPaymentDetails(){
        ArrayList<Object[]> rowDatas=Availability.rows;
        ArrayList<RoomDTO> roomDetails=new ArrayList<>();
        for (Object[] rowData : rowDatas) {
            RoomDTO r=new RoomDTO(rowData[0].toString(),rowData[1].toString(),rowData[2].toString(),Double.parseDouble(rowData[3].toString()));
            roomDetails.add(r);
        }
        for (RoomDTO r : roomDetails) {
            total+=r.getRoomPrice();
        }
        double nights=ReservationForm.noOfNights;
        lblAmount.setText(""+total*nights);
        lblAdvancePayment.setText(""+(total*nights)/2);
        
        Availability.rows.clear();
    }
    
    private void setGuestID_ResID(){
        lblGuestID.setText(AddGuest.guestID);
        lblResID.setText(ReservationForm.resID);
    }
    
    private void setSystemDate(){
        Date d1=new Date();
        SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        String formatDate=df.format(d1);
        lblPaymentDate.setText(formatDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblAmount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RBCard = new javax.swing.JRadioButton();
        RBCash = new javax.swing.JRadioButton();
        RBCheque = new javax.swing.JRadioButton();
        creditDebitPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        lblAdvancePayment = new javax.swing.JLabel();
        lblConfirm = new javax.swing.JLabel();
        lblBack1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPaymentDate = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblResID = new javax.swing.JLabel();
        lblGuestID = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 620));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAmount.setFont(new java.awt.Font("Tahoma", 0, 44)); // NOI18N
        lblAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 230, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Reservation ID :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 170, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Guest ID :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 170, 30));

        RBCard.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RBCard);
        RBCard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBCard.setText("Pay By Credit/Debit Card");
        RBCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RBCardMouseClicked(evt);
            }
        });
        RBCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBCardActionPerformed(evt);
            }
        });
        add(RBCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 230, -1));

        RBCash.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RBCash);
        RBCash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBCash.setText("Pay By Cash");
        RBCash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RBCashMouseClicked(evt);
            }
        });
        RBCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBCashActionPerformed(evt);
            }
        });
        add(RBCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 140, -1));

        RBCheque.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RBCheque);
        RBCheque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBCheque.setText("Pay By Cheque");
        RBCheque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RBChequeMouseClicked(evt);
            }
        });
        RBCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBChequeActionPerformed(evt);
            }
        });
        add(RBCheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 170, -1));

        creditDebitPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Credit Card or Debit Card Payment");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Credit Card or Debit Card Number :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Payment Type :");

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton4.setText("Visa");

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton5.setText("Master Card");

        javax.swing.GroupLayout creditDebitPanelLayout = new javax.swing.GroupLayout(creditDebitPanel);
        creditDebitPanel.setLayout(creditDebitPanelLayout);
        creditDebitPanelLayout.setHorizontalGroup(
            creditDebitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditDebitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(creditDebitPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(creditDebitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creditDebitPanelLayout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addGap(27, 27, 27)
                        .addComponent(jRadioButton5))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(creditDebitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        creditDebitPanelLayout.setVerticalGroup(
            creditDebitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditDebitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creditDebitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        add(creditDebitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 330, 230));

        lblAdvancePayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAdvancePayment.setForeground(new java.awt.Color(102, 102, 102));
        add(lblAdvancePayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 220, 50));

        lblConfirm.setBackground(new java.awt.Color(221, 188, 9));
        lblConfirm.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirm.setText("Confirm");
        lblConfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblConfirm.setName("lblMain"); // NOI18N
        lblConfirm.setOpaque(true);
        lblConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConfirmMouseExited(evt);
            }
        });
        add(lblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, 170, 50));

        lblBack1.setBackground(new java.awt.Color(221, 188, 9));
        lblBack1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblBack1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack1.setText("Back");
        lblBack1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBack1.setName("lblMain"); // NOI18N
        lblBack1.setOpaque(true);
        lblBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBack1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBack1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBack1MouseExited(evt);
            }
        });
        add(lblBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 170, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Choose Payment Method ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 370, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        jLabel8.setText("Total Amount :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 330, 70));

        lblPaymentDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPaymentDate.setForeground(new java.awt.Color(102, 102, 102));
        add(lblPaymentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 200, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Advance Payment :");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 230, 40));

        lblResID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblResID.setForeground(new java.awt.Color(102, 102, 102));
        add(lblResID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 200, 30));

        lblGuestID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGuestID.setForeground(new java.awt.Color(102, 102, 102));
        add(lblGuestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 200, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Payment Date :");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void RBCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBCardMouseClicked
        creditDebitPanel.setVisible(true);
    }//GEN-LAST:event_RBCardMouseClicked

    private void RBCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBCardActionPerformed

    private void RBCashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBCashMouseClicked
        creditDebitPanel.setVisible(false);
    }//GEN-LAST:event_RBCashMouseClicked

    private void RBCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBCashActionPerformed

    private void RBChequeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBChequeMouseClicked
        creditDebitPanel.setVisible(false);
    }//GEN-LAST:event_RBChequeMouseClicked

    private void RBChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBChequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBChequeActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void lblConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseClicked
        try {
            String pid=IDGenerator.getNewID("Payment", "PID", "P");
            String rid=lblResID.getText();
            double amountPaid=Double.parseDouble(lblAdvancePayment.getText());
            String date=lblPaymentDate.getText();
            String method=getSelectedButtonText();
            PaymentDTO p1=new PaymentDTO(pid,rid,amountPaid,date,method);
            boolean result=ctrlPayment.add(p1);
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblConfirmMouseClicked

    private void lblBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBack1MouseClicked
        //new ReservationForm().setVisible(true);
        
    }//GEN-LAST:event_lblBack1MouseClicked

    private void lblConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseEntered
        lblConfirm.setBackground(new Color(255,162,0));
        lblConfirm.setOpaque(true);
    }//GEN-LAST:event_lblConfirmMouseEntered

    private void lblConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseExited
        lblConfirm.setBackground(new Color(221,188,9));
        lblConfirm.setOpaque(true);
    }//GEN-LAST:event_lblConfirmMouseExited

    private void lblBack1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBack1MouseEntered
        lblBack1.setBackground(new Color(255,162,0));
        lblBack1.setOpaque(true);
    }//GEN-LAST:event_lblBack1MouseEntered

    private void lblBack1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBack1MouseExited
        lblBack1.setBackground(new Color(221,188,9));
        lblBack1.setOpaque(true);
    }//GEN-LAST:event_lblBack1MouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Reception.reserveRoomPanel.setVisible(false);
        Reception.pnlViewReports.setVisible(false);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBCard;
    private javax.swing.JRadioButton RBCash;
    private javax.swing.JRadioButton RBCheque;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel creditDebitPanel;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAdvancePayment;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblBack1;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblGuestID;
    private javax.swing.JLabel lblPaymentDate;
    private javax.swing.JLabel lblResID;
    // End of variables declaration//GEN-END:variables

    private String getSelectedButtonText() {
        RBCard.setActionCommand("Card");
        RBCash.setActionCommand("Cash");
        RBCheque.setActionCommand("Cheque");
        return buttonGroup1.getSelection().getActionCommand();
    }

    
}
