/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.gdse41.sem1project.view.panels;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import edu.gdse41.sem1project.view.Reception;
import edu.gdse41.sem1project.view.panels.titles.AvailabilityTitle;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author Hansani Kariyawasam
 */
public class SearchRooms extends javax.swing.JPanel {
    
    public static String checkIn;
    public static String checkOut;
    public static String noOfAdults;
    public static String noOfKids;

    /**
     * Creates new form SearchRooms
     */
    public SearchRooms() {
        initComponents();
    }
    
    private void loadPanel(JPanel pane){
        pnlCover.removeAll();
        pnlCover.revalidate();
        pnlCover.add(pane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlCover = new javax.swing.JPanel();
        txtCheckIn = new org.jdesktop.swingx.JXDatePicker();
        txtCheckOut = new org.jdesktop.swingx.JXDatePicker();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        cmbAdults = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        cmbKids = new javax.swing.JComboBox();
        lblSearch = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCover.setBackground(new java.awt.Color(255, 255, 255));
        pnlCover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCoverMouseClicked(evt);
            }
        });
        pnlCover.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pnlCoverPropertyChange(evt);
            }
        });
        pnlCover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckInActionPerformed(evt);
            }
        });
        txtCheckIn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCheckInPropertyChange(evt);
            }
        });
        pnlCover.add(txtCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, 30));

        txtCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckOutActionPerformed(evt);
            }
        });
        txtCheckOut.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCheckOutPropertyChange(evt);
            }
        });
        pnlCover.add(txtCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 200, 30));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Superior Double");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlCover.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 150, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("Standard Double");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlCover.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 160, -1));

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setText("Basic Double");
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlCover.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 170, -1));

        cmbAdults.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "     ", "1", "2", "3", "4", "5", "6" }));
        cmbAdults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAdultsActionPerformed(evt);
            }
        });
        pnlCover.add(cmbAdults, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 120, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "Whole villa" }));
        pnlCover.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 120, 30));

        cmbKids.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "    ", "0", "1", "2", "3", "4" }));
        cmbKids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKidsActionPerformed(evt);
            }
        });
        pnlCover.add(cmbKids, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 110, 30));

        lblSearch.setBackground(new java.awt.Color(221, 188, 9));
        lblSearch.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setText("Search");
        lblSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSearch.setName("lblMain"); // NOI18N
        lblSearch.setOpaque(true);
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchMouseExited(evt);
            }
        });
        pnlCover.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, 170, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Check-In-Date");
        pnlCover.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 270, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Kids");
        pnlCover.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 130, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/gdse41/sem1project/resources/images/Basic.png"))); // NOI18N
        pnlCover.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 155, 130));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/gdse41/sem1project/resources/images/Superior.png"))); // NOI18N
        pnlCover.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 155, 130));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/gdse41/sem1project/resources/images/Standard.png"))); // NOI18N
        pnlCover.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 155, 130));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Check-Out-Date");
        pnlCover.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 270, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("No of Rooms");
        pnlCover.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 130, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("Adults");
        pnlCover.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 130, 40));

        add(pnlCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked

        Date checkInDate=txtCheckIn.getDate();
        Date checkOutDate=txtCheckOut.getDate();
        DateFormat fmt=new SimpleDateFormat("yyyy-MM-dd");

        SearchRooms.checkIn=fmt.format(checkInDate);
        SearchRooms.checkOut=fmt.format(checkOutDate);
//        
//        Reception.checkIn=fmt.format(checkInDate);
//        Reception.checkOut=fmt.format(checkOutDate);
        
        Reception frmMain = (Reception) (JFrame) SwingUtilities.getWindowAncestor(this);
        frmMain.pnlMain.removeAll();
        //Availability a = new Availability();
        frmMain.pnlMain.add(new Availability());
        frmMain.pnltitle.removeAll();
        AvailabilityTitle at=new AvailabilityTitle();
        frmMain.pnltitle.add(at);
        frmMain.pnlMain.updateUI();

            
//        //new Availability().setVisible(true);
//        Reception.loadStaticPanel(new Availability());
        
    }//GEN-LAST:event_lblSearchMouseClicked

    private void txtCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckInActionPerformed
        Reception.reserveRoomPanel.setVisible(false);
    }//GEN-LAST:event_txtCheckInActionPerformed

    private void cmbAdultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAdultsActionPerformed
        noOfAdults=(String) cmbAdults.getSelectedItem();
    }//GEN-LAST:event_cmbAdultsActionPerformed

    private void cmbKidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKidsActionPerformed
        noOfKids=(String) cmbKids.getSelectedItem();
    }//GEN-LAST:event_cmbKidsActionPerformed

    private void lblSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseEntered
        lblSearch.setBackground(new Color(255,162,0));
        lblSearch.setOpaque(true);
    }//GEN-LAST:event_lblSearchMouseEntered

    private void lblSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseExited
        lblSearch.setBackground(new Color(221,188,9));
        lblSearch.setOpaque(true);
    }//GEN-LAST:event_lblSearchMouseExited

    private void pnlCoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCoverMouseClicked
        Reception.reserveRoomPanel.setVisible(false);
        Reception.pnlViewReports.setVisible(false);
    }//GEN-LAST:event_pnlCoverMouseClicked

    private void txtCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckOutActionPerformed
        Reception.reserveRoomPanel.setVisible(false);
        Reception.pnlViewReports.setVisible(false);        
    }//GEN-LAST:event_txtCheckOutActionPerformed

    private void txtCheckOutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCheckOutPropertyChange
        txtCheckOut.getMonthView().setLowerBound(txtCheckIn.getDate());
    }//GEN-LAST:event_txtCheckOutPropertyChange

    private void pnlCoverPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pnlCoverPropertyChange
        txtCheckIn.getMonthView().setLowerBound(new Date());
    }//GEN-LAST:event_pnlCoverPropertyChange

    private void txtCheckInPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCheckInPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckInPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbAdults;
    private javax.swing.JComboBox cmbKids;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel pnlCover;
    private org.jdesktop.swingx.JXDatePicker txtCheckIn;
    private org.jdesktop.swingx.JXDatePicker txtCheckOut;
    // End of variables declaration//GEN-END:variables
}
